language: cpp
dist: xenial

matrix:
  fast_finish: true
  include:
    - os: linux
      name: "GCC 5"

    - os: linux
      name: "GCC 9"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
      env:
         - MATRIX_EVAL="CC=gcc-9 && CXX=g++-9"

    - os: linux
      name: "Clang 3.5"
      addons:
        apt:
          packages:
            - clang-3.5
      env:
        - MATRIX_EVAL="CC=clang-3.5 && CXX=clang++-3.5"

    - os: linux
      name: "Clang 8"
      addons:
        apt:
          sources:
            - llvm-toolchain-xenial-8
          packages:
            - clang-8
      env:
         - MATRIX_EVAL="CC=clang-8 && CXX=clang++-8"

    - os: windows
      name: "MSVC"
         
before_install:
    - eval "${MATRIX_EVAL}"

script:
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build . -j 4
  - ctest --verbose
