name: build

on: [push]

env:
  BUILD_TYPE: Release
  ARCH: amd64

jobs:
  build-linux:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: G++ 7 & GCOV
            CC: gcc-7
            CXX: g++-7
            use-gcov: true
            install: g++-7
          - name: Clang 5
            CC: clang-5.0
            CXX: clang++-5.0
            install: clang-5.0

    env:
      CC: ${{matrix.CC}}
      CXX: ${{matrix.CXX}}
      USE_GCOV: ${{matrix.use-gcov == true}}

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install compiler
        if: ${{matrix.install}}
        run: sudo apt install ${{matrix.install}}

      - name: Configure stuff
        run: |
          mkdir ${{github.workspace}}/build
          cd ${{github.workspace}}/build
          cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DUSE_GCOV=$USE_GCOV ..

      - name: Build
        working-directory: ${{github.workspace}}/build
        run: cmake --build . -j 6

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest --output-on-failure

      - name: Upload coverage report
        working-directory: ${{github.workspace}}
        if: ${{matrix.use-gcov == true}}
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.CoverallsToken }}
        run: |
          sudo apt install python3-setuptools python3-idna python3-requests python3-urllib3
          git clone https://github.com/PredatorCZ/cpp-coveralls.git
          pushd cpp-coveralls
          sudo python3 setup.py install
          popd
          export COVERALLS_SERVICE_NAME="gitlab-ci"
          coveralls -E ".*/build/.*.[ch]((pp)|(c)|(xx))?$" -e test -e 3rd_party --gcov-options '\-lp' > /dev/null

  build-widle:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Configure stuff
        run: |
          mkdir ${{github.workspace}}/build
          cd ${{github.workspace}}/build
          cmake -DCMAKE_BUILD_TYPE=Release -A x64 ..
      - name: Build
        working-directory: ${{github.workspace}}/build
        run: |
          cmake --build . -j 6 --config Release

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest --output-on-failure -C Release
