name: build

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  build-linux:
    runs-on: ubuntu-16.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - CC: gcc-5
            CXX: g++-5
            artifacts: true
          - CC: gcc-9
            CXX: g++-9
          - CC: clang-3.5
            CXX: clang++-3.5
            install: true
          - CC: clang-9
            CXX: clang++-9

    env:
      CC: ${{matrix.CC}}
      CXX: ${{matrix.CXX}}

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install compiler
        if: ${{matrix.install == true}}
        run: sudo apt install ${{matrix.CC}}

      - name: Configure stuff
        run: |
          mkdir ${{github.workspace}}/build
          cd ${{github.workspace}}/build
          cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE ..

      - name: Build
        working-directory: ${{github.workspace}}/build
        run: cmake --build . -j 6

      - name: Install
        if: ${{matrix.artifacts == true}}
        working-directory: ${{github.workspace}}/build
        run: cmake --build . --target install

      - name: Upload Artifacts
        if: ${{matrix.artifacts == true}}
        uses: actions/upload-artifact@v2
        with:
          name: RevilToolset-xenial
          path: |
            ${{github.workspace}}/bin/*
            ${{github.workspace}}/LICENSE.md
            ${{github.workspace}}/README.md
          retention-days: 5

  build-widle:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Configure stuff
        run: |
          mkdir ${{github.workspace}}/build
          cd ${{github.workspace}}/build
          cmake -DCMAKE_BUILD_TYPE=Release -A x64 ..
      - name: Build
        working-directory: ${{github.workspace}}/build
        run: cmake --build . -j 6 --config Release

      - name: Install
        working-directory: ${{github.workspace}}/build
        run: cmake --build . --target install --config Release

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: RevilToolset-win64
          path: |
            ${{github.workspace}}/bin/*
            ${{github.workspace}}/LICENSE.md
            ${{github.workspace}}/README.md
          retention-days: 5
